site_name: C# Source Generation templates
theme: readthedocs
edit_uri: https://github.com/sandervanteinde/SourceGenTemplates/tree/master/github-docs/docs
repo_url: https://github.com/sandervanteinde/SourceGenTemplates
repo_name: GitHub
plugins:
  - macros

nav:
  - Home: index.md
  - 'Getting started':
      - Installation: getting-started/index.md
      - 'First template': getting-started/first-template.md
  - Samples:
      - Overview: samples/index.md
      - 'Generate builder pattern': samples/generate-builder.md
  - Language:
      - Concepts: language/index.md
      - 'Control directives': language/control-directives.md
      - 'Boolean expressions': language/boolean-expressions.md
      - Mutators: language/mutators.md
      - Grammar: language/grammar.md
  - Variables:
      - Overview: variable-types/index.md
      - Class: variable-types/class.md
      - Field: variable-types/field.md
      - Integer: variable-types/integer.md
      - Namespace: variable-types/namespace.md
      - Property: variable-types/property.md
      - String: variable-types/string.md
      - Type: variable-types/type.md
      - 'Variable collection': variable-types/variable-collection.md

extra:
  nugetpackagename: SourceGenTemplates
  packagename: C# Source Generation Template