name: Build GH-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5.1.0
      - name: Install mkdocs
        run: pip install mkdocs
      - name: Install macros
        run: pip install mkdocs-macros-plugin
      - name: Build website
        run: mkdocs build -f mkdocs.yml
        working-directory: github-docs
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: github-docs/site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
