name: Build GH-Pages
env:
  PUBLISH_DIR: wwwroot

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5.1.0
      - name: Install mkdocs
        run: pip install mkdocs
      - name: Install macros
        run: pip install mkdocs-macros-plugin
      - name: Build website
        run: mkdocs build -f github-docs/mkdocs.yml -d ${{ env.PUBLISH_DIR }}
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: ${{ env.PUBLISH_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
